000100160115/*USRVALPRG- second program                                          */                             
000200160115                                                                                                    
000300160115PGM                                                                                                 
000400160115                                                                                                    
000500160118  WRKOBJPDM LIB(DW233F02)                                                                           
000600160115  DSPMSG                                                                                            
000700160115  WRKSPLF                                                                                           
000800160115                                                                                                    
000900160115ENDPGM                                                                                              
